Resources: 
  CognitoUserPool: 
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.stage}-user-pool

      UsernameAttributes: 
        - email

      AutoVerifiedAttributes: 
        - email

  CognitoUserPoolClient: 
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.stage}-user-pool-client
      UserPoolId:
        Ref: CognitoUSerPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

      GenerateSecret: false



Outputs: 
  UserPoolId: 
    Value: 
      Ref: CognitoUserPool

  UserPoolClientId: 
    Value: 
      Ref: CognitoUserPoolClient

        
